### ISSUE TITLE
ROLES: 404 error auf integration für roles#new/edit

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sac_cas#1072]
### Aktuelles Verhalten

Beim Klick auf "Person hinzufügen" bei einer beliebigen Personen-Liste auf der Integrationsumgebung erscheint ein **404** error. 
Das Verhalten lässt sich lokal im Dev-Env nicht nachvollziehen.
Passiert nur beim der SAC Integrations-Umgebung, andere Umgebungen scheinen bisher nicht betroffen.

### Gewünschtes Verhalten

es können Rollen erfasst und editiert werden. 

### Schritte zu reproduzieren

1. Login auf der Integration mit beliebigem User/Person
2. Aufrufen einer Personenliste einer beliebigen Gruppe
3. Klick auf "Person hinzufügen"
4. 404 ...

### hitobito version

2.3.0

### Organisation

sac_cas

**Comment by mtnstar** [comment]
bisher erfolglose Versuche dem Problem auf den Grund zu gehen:

- Neu releasen/deployen der Integrations-Umgebung, 404 ...
- Verbinden der Integrations-DB mit der lokalen Entwicklungsumgebung
  - Funktioniert lokal einwandfrei
- Verbinden auf den Rails Server der Integrations-Umgebung per Portforwarding um den Nginx zu umgehen, 404 ...

**Comment by mtnstar** [comment]
Log

```
[56656a11-bcb4-4ad2-a51f-162622c8cacb] {"method":"GET","path":"/de/groups/3819/roles/new","format":"html","controller":"RolesController","action":"new","status":404,"error":"ActionController::RoutingError: Not Found","allocations":39402,"duration":67.75,"view":0.0,"db":0.0,"time":"2024-10-02 12:52:41 +0200","request_uuid":"56656a11-bcb4-4ad2-a51f-162622c8cacb","params":"{locale: 'de', group_id: '3819'}","backtrace":["app/controllers/application_controller.rb:66:in `not_found'"],"user_id":600000}
[56656a11-bcb4-4ad2-a51f-162622c8cacb]
[56656a11-bcb4-4ad2-a51f-162622c8cacb] ActionController::RoutingError (Not Found):
[56656a11-bcb4-4ad2-a51f-162622c8cacb]
[56656a11-bcb4-4ad2-a51f-162622c8cacb] app/controllers/application_controller.rb:66:in `not_found'
[56656a11-bcb4-4ad2-a51f-162622c8cacb] Didn't expect RescueRegistry context to be set in controller
[56656a11-bcb4-4ad2-a51f-162622c8cacb] {"method":"GET","path":"/404","format":"html","controller":"ErrorsController","action":"show404","status":404,"allocations":2861,"duration":3.38,"view":3.09,"db":0.0,"time":"2024-10-02 12:52:41 +0200","request_uuid":null,"params":"{locale: 'de', group_id: '3819'}"
```

**Comment by mtnstar** [comment]
hat es ggf. was mit dem im application_controller definierten lines zu tun?:

```
  if Rails.env.production?
    rescue_from ActionController::UnknownFormat,
      ActionView::MissingTemplate,
      with: :not_found
  end
```

**Comment by mtnstar** [comment]
das problem war das ein partial aus dem core welches aus dem wagon heraus gerendert wurde nicht via einen relativen pfad erreichbar was in der prod umgebung.
neu gibt es jetzt einen view helper dafür: https://github.com/hitobito/hitobito_sac_cas/pull/1073/files
