### ISSUE TITLE
SPECS: Flaky Spec GroupResource reads_spec

### ISSUE THREAD

**Issue by Largo** [hitobito/hitobito_sac_cas#821]
### Welche Spec ist fehlgeschlagen?

./spec/resources/group/reads_spec.rb:169  GroupResource extra attributes membership_self_registration_url returns the self registration url for ortsgruppe

### Welcher Seed wurde verwendet?

46975

### Stacktrace

[Events: E-Mail Aufgebot (#633) · hitobito/hitobito_sac_cas@e01dddd](https://github.com/hitobito/hitobito_sac_cas/actions/runs/10349306446/job/28643387750)

[Update CustomContent · hitobito/hitobito_sac_cas@9429ad7](https://github.com/hitobito/hitobito_sac_cas/actions/runs/10365498667/job/28692752990)

[PEOPLE: Wizard SAC Austritt termination_by_section_only check erweitern · hitobito/hitobito_sac_cas@0563f9b](https://github.com/hitobito/hitobito_sac_cas/actions/runs/10364432417/job/28689705415)

```
 1) GroupResource extra attributes membership_self_registration_url returns the self registration url for ortsgruppe
     Failure/Error: object.sac_cas_self_registration_url(helpers.request.host)

     NoMethodError:
       undefined method `host' for nil:NilClass
     # ./app/decorators/sac_cas/group_decorator.rb:26:in `membership_self_registration_url'
     # ./app/resources/sac_cas/group_resource.rb:48:in `block (2 levels) in <module:GroupResource>'
     # ./vendor/bundle/ruby/3.2.0/gems/graphiti-1.3.9/lib/graphiti/util/serializer_attributes.rb:138:in `instance_eval'
     # ./vendor/bundle/ruby/3.2.0/gems/graphiti-1.3.9/lib/graphiti/util/serializer_attributes.rb:138:in `block in wrap_proc'
     # ./vendor/bundle/ruby/3.2.0/gems/jsonapi-serializable-0.3.1/lib/jsonapi/serializable/resource.rb:46:in `instance_eval'
     # ./vendor/bundle/ruby/3.2.0/gems/jsonapi-serializable-0.3.1/lib/jsonapi/serializable/resource.rb:46:in `block in as_jsonapi'
     # ./vendor/bundle/ruby/3.2.0/gems/jsonapi-serializable-0.3.1/lib/jsonapi/serializable/resource.rb:45:in `each'
     # ./vendor/bundle/ruby/3.2.0/gems/jsonapi-serializable-0.3.1/lib/jsonapi/serializable/resource.rb:45:in `each_with_object'
     # ./vendor/bundle/ruby/3.2.0/gems/jsonapi-serializable-0.3.1/lib/jsonapi/serializable/resource.rb:45:in `as_jsonapi'
     # ./vendor/bundle/ruby/3.2.0/gems/graphiti-1.3.9/lib/graphiti/serializer.rb:67:in `as_jsonapi'
     # ./vendor/bundle/ruby/3.2.0/gems/graphiti-1.3.9/lib/graphiti/extensions/temp_id.rb:15:in `as_jsonapi'
     # ./vendor/bundle/ruby/3.2.0/gems/jsonapi-renderer-0.2.2/lib/jsonapi/renderer/simple_resources_processor.rb:13:in `block (2 levels) in process_resources'
     # ./vendor/bundle/ruby/3.2.0/gems/jsonapi-renderer-0.2.2/lib/jsonapi/renderer/simple_resources_processor.rb:9:in `map!'
     # ./vendor/bundle/ruby/3.2.0/gems/jsonapi-renderer-0.2.2/lib/jsonapi/renderer/simple_resources_processor.rb:9:in `block in process_resources'
     # ./vendor/bundle/ruby/3.2.0/gems/jsonapi-renderer-0.2.2/lib/jsonapi/renderer/simple_resources_processor.rb:8:in `each'
     # ./vendor/bundle/ruby/3.2.0/gems/jsonapi-renderer-0.2.2/lib/jsonapi/renderer/simple_resources_processor.rb:8:in `process_resources'
     # ./vendor/bundle/ruby/3.2.0/gems/jsonapi-renderer-0.2.2/lib/jsonapi/renderer/resources_processor.rb:13:in `process'
     # ./vendor/bundle/ruby/3.2.0/gems/jsonapi-renderer-0.2.2/lib/jsonapi/renderer/document.rb:49:in `data_hash'
     # ./vendor/bundle/ruby/3.2.0/gems/jsonapi-renderer-0.2.2/lib/jsonapi/renderer/document.rb:35:in `block in document_hash'
     # ./vendor/bundle/ruby/3.2.0/gems/jsonapi-renderer-0.2.2/lib/jsonapi/renderer/document.rb:31:in `document_hash'
     # ./vendor/bundle/ruby/3.2.0/gems/jsonapi-renderer-0.2.2/lib/jsonapi/renderer/document.rb:22:in `to_hash'
     # ./vendor/bundle/ruby/3.2.0/gems/jsonapi-renderer-0.2.2/lib/jsonapi/renderer.rb:22:in `render'
     # ./vendor/bundle/ruby/3.2.0/gems/jsonapi-serializable-0.3.1/lib/jsonapi/serializable/renderer.rb:47:in `render'
     # ./vendor/bundle/ruby/3.2.0/gems/graphiti-1.3.9/lib/graphiti/renderer.rb:71:in `block in render'
     # ./vendor/bundle/ruby/3.2.0/gems/graphiti-1.3.9/lib/graphiti.rb:65:in `block in broadcast'
     # ./vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.7/lib/active_support/notifications.rb:203:in `block in instrument'
     # ./vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.7/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
     # ./vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.7/lib/active_support/notifications.rb:203:in `instrument'
     # ./vendor/bundle/ruby/3.2.0/gems/graphiti-1.3.9/lib/graphiti.rb:64:in `broadcast'
     # ./vendor/bundle/ruby/3.2.0/gems/graphiti-1.3.9/lib/graphiti/renderer.rb:58:in `render'
     # ./vendor/bundle/ruby/3.2.0/gems/graphiti-1.3.9/lib/graphiti/renderer.rb:17:in `to_jsonapi'
     # ./vendor/bundle/ruby/3.2.0/gems/graphiti-1.3.9/lib/graphiti/resource_proxy.rb:43:in `to_jsonapi'
     # ./vendor/bundle/ruby/3.2.0/gems/graphiti_spec_helpers-1.1.0/lib/graphiti_spec_helpers/rspec.rb:35:in `render'
     # ./spec/resources/group/reads_spec.rb:169:in `block (4 levels) in <top (required)>'
     # /home/runner/work/hitobito_sac_cas/hitobito_sac_cas/hitobito/spec/support/resource_spec_helper.rb:24:in `block (4 levels) in <module:ResourceSpecHelper>'
     # ./vendor/bundle/ruby/3.2.0/gems/graphiti-1.3.9/lib/graphiti.rb:33:in `with_context'
     # /home/runner/work/hitobito_sac_cas/hitobito_sac_cas/hitobito/spec/support/resource_spec_helper.rb:24:in `block (3 levels) in <module:ResourceSpecHelper>'
     # /home/runner/work/hitobito_sac_cas/hitobito_sac_cas/hitobito/spec/support/resource_spec_helper.rb:23:in `block (2 levels) in <module:ResourceSpecHelper>'
     # ./vendor/bundle/ruby/3.2.0/gems/graphiti_spec_helpers-1.1.0/lib/graphiti_spec_helpers/rspec.rb:13:in `block (3 levels) in <top (required)>'
     # ./vendor/bundle/ruby/3.2.0/gems/graphiti-1.3.9/lib/graphiti.rb:33:in `with_context'
     # ./vendor/bundle/ruby/3.2.0/gems/graphiti_spec_helpers-1.1.0/lib/graphiti_spec_helpers/rspec.rb:12:in `block (2 levels) in <top (required)>'
     # /home/runner/work/hitobito_sac_cas/hitobito_sac_cas/hitobito/spec/spec_helper.rb:145:in `block (2 levels) in <top (required)>'
     # ./vendor/bundle/ruby/3.2.0/gems/webmock-3.23.1/lib/webmock/rspec.rb:39:in `block (2 levels) in <top (required)>'
     # ./vendor/bundle/ruby/3.2.0/gems/rspec-core-3.13.0/exe/rspec:4:in `<main>'

  2) GroupResource extra attributes membership_self_registration_url returns the self registration url for sektion
     Failure/Error: object.sac_cas_self_registration_url(helpers.request.host)

     NoMethodError:
       undefined method `host' for nil:NilClass
     # ./app/decorators/sac_cas/group_decorator.rb:26:in `membership_self_registration_url'
     # ./app/resources/sac_cas/group_resource.rb:48:in `block (2 levels) in <module:GroupResource>'
     # ./vendor/bundle/ruby/3.2.0/gems/graphiti-1.3.9/lib/graphiti/util/serializer_attributes.rb:138:in `instance_eval'
     # ./vendor/bundle/ruby/3.2.0/gems/graphiti-1.3.9/lib/graphiti/util/serializer_attributes.rb:138:in `block in wrap_proc'
     # ./vendor/bundle/ruby/3.2.0/gems/jsonapi-serializable-0.3.1/lib/jsonapi/serializable/resource.rb:46:in `instance_eval'
     # ./vendor/bundle/ruby/3.2.0/gems/jsonapi-serializable-0.3.1/lib/jsonapi/serializable/resource.rb:46:in `block in as_jsonapi'
     # ./vendor/bundle/ruby/3.2.0/gems/jsonapi-serializable-0.3.1/lib/jsonapi/serializable/resource.rb:45:in `each'
     # ./vendor/bundle/ruby/3.2.0/gems/jsonapi-serializable-0.3.1/lib/jsonapi/serializable/resource.rb:45:in `each_with_object'
     # ./vendor/bundle/ruby/3.2.0/gems/jsonapi-serializable-0.3.1/lib/jsonapi/serializable/resource.rb:45:in `as_jsonapi'
     # ./vendor/bundle/ruby/3.2.0/gems/graphiti-1.3.9/lib/graphiti/serializer.rb:67:in `as_jsonapi'
     # ./vendor/bundle/ruby/3.2.0/gems/graphiti-1.3.9/lib/graphiti/extensions/temp_id.rb:15:in `as_jsonapi'
     # ./vendor/bundle/ruby/3.2.0/gems/jsonapi-renderer-0.2.2/lib/jsonapi/renderer/simple_resources_processor.rb:13:in `block (2 levels) in process_resources'
     # ./vendor/bundle/ruby/3.2.0/gems/jsonapi-renderer-0.2.2/lib/jsonapi/renderer/simple_resources_processor.rb:9:in `map!'
     # ./vendor/bundle/ruby/3.2.0/gems/jsonapi-renderer-0.2.2/lib/jsonapi/renderer/simple_resources_processor.rb:9:in `block in process_resources'
     # ./vendor/bundle/ruby/3.2.0/gems/jsonapi-renderer-0.2.2/lib/jsonapi/renderer/simple_resources_processor.rb:8:in `each'
     # ./vendor/bundle/ruby/3.2.0/gems/jsonapi-renderer-0.2.2/lib/jsonapi/renderer/simple_resources_processor.rb:8:in `process_resources'
     # ./vendor/bundle/ruby/3.2.0/gems/jsonapi-renderer-0.2.2/lib/jsonapi/renderer/resources_processor.rb:13:in `process'
     # ./vendor/bundle/ruby/3.2.0/gems/jsonapi-renderer-0.2.2/lib/jsonapi/renderer/document.rb:49:in `data_hash'
     # ./vendor/bundle/ruby/3.2.0/gems/jsonapi-renderer-0.2.2/lib/jsonapi/renderer/document.rb:35:in `block in document_hash'
     # ./vendor/bundle/ruby/3.2.0/gems/jsonapi-renderer-0.2.2/lib/jsonapi/renderer/document.rb:31:in `document_hash'
     # ./vendor/bundle/ruby/3.2.0/gems/jsonapi-renderer-0.2.2/lib/jsonapi/renderer/document.rb:22:in `to_hash'
     # ./vendor/bundle/ruby/3.2.0/gems/jsonapi-renderer-0.2.2/lib/jsonapi/renderer.rb:22:in `render'
     # ./vendor/bundle/ruby/3.2.0/gems/jsonapi-serializable-0.3.1/lib/jsonapi/serializable/renderer.rb:47:in `render'
     # ./vendor/bundle/ruby/3.2.0/gems/graphiti-1.3.9/lib/graphiti/renderer.rb:71:in `block in render'
     # ./vendor/bundle/ruby/3.2.0/gems/graphiti-1.3.9/lib/graphiti.rb:65:in `block in broadcast'
     # ./vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.7/lib/active_support/notifications.rb:203:in `block in instrument'
     # ./vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.7/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
     # ./vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.7/lib/active_support/notifications.rb:203:in `instrument'
     # ./vendor/bundle/ruby/3.2.0/gems/graphiti-1.3.9/lib/graphiti.rb:64:in `broadcast'
     # ./vendor/bundle/ruby/3.2.0/gems/graphiti-1.3.9/lib/graphiti/renderer.rb:58:in `render'
     # ./vendor/bundle/ruby/3.2.0/gems/graphiti-1.3.9/lib/graphiti/renderer.rb:17:in `to_jsonapi'
     # ./vendor/bundle/ruby/3.2.0/gems/graphiti-1.3.9/lib/graphiti/resource_proxy.rb:43:in `to_jsonapi'
     # ./vendor/bundle/ruby/3.2.0/gems/graphiti_spec_helpers-1.1.0/lib/graphiti_spec_helpers/rspec.rb:35:in `render'
     # ./spec/resources/group/reads_spec.rb:162:in `block (4 levels) in <top (required)>'
     # /home/runner/work/hitobito_sac_cas/hitobito_sac_cas/hitobito/spec/support/resource_spec_helper.rb:24:in `block (4 levels) in <module:ResourceSpecHelper>'
     # ./vendor/bundle/ruby/3.2.0/gems/graphiti-1.3.9/lib/graphiti.rb:33:in `with_context'
     # /home/runner/work/hitobito_sac_cas/hitobito_sac_cas/hitobito/spec/support/resource_spec_helper.rb:24:in `block (3 levels) in <module:ResourceSpecHelper>'
     # /home/runner/work/hitobito_sac_cas/hitobito_sac_cas/hitobito/spec/support/resource_spec_helper.rb:23:in `block (2 levels) in <module:ResourceSpecHelper>'
     # ./vendor/bundle/ruby/3.2.0/gems/graphiti_spec_helpers-1.1.0/lib/graphiti_spec_helpers/rspec.rb:13:in `block (3 levels) in <top (required)>'
     # ./vendor/bundle/ruby/3.2.0/gems/graphiti-1.3.9/lib/graphiti.rb:33:in `with_context'
     # ./vendor/bundle/ruby/3.2.0/gems/graphiti_spec_helpers-1.1.0/lib/graphiti_spec_helpers/rspec.rb:12:in `block (2 levels) in <top (required)>'
     # /home/runner/work/hitobito_sac_cas/hitobito_sac_cas/hitobito/spec/spec_helper.rb:145:in `block (2 levels) in <top (required)>'
     # ./vendor/bundle/ruby/3.2.0/gems/webmock-3.23.1/lib/webmock/rspec.rb:39:in `block (2 levels) in <top (required)>'
     # ./vendor/bundle/ruby/3.2.0/gems/rspec-core-3.13.0/exe/rspec:4:in `<main>'

Finished in 2 minutes 35.9 seconds (files took 13.1 seconds to load)
2278 examples, 2 failures, 3 pending

Failed examples:

rspec ./spec/resources/group/reads_spec.rb:167 # GroupResource extra attributes membership_self_registration_url returns the self registration url for ortsgruppe
rspec ./spec/resources/group/reads_spec.rb:160 # GroupResource extra attributes membership_self_registration_url returns the self registration url for sektion
```

**Comment by Largo** [comment]
Wieder aufgetreten: 
- [fix sac_event development seeder · hitobito/hitobito_sac_cas@4666ce8](https://github.com/hitobito/hitobito_sac_cas/actions/runs/10401957872/attempts/1)

**Comment by Largo** [comment]
Rspec bisect:
```
rspec --tag ~type:feature --seed 106 --bisect
Bisect started using options: "--tag ~type:feature --seed 106"
Running suite to find failures... (3 minutes 1.2 seconds)
Starting bisect with 2 failing examples and 2287 non-failing examples.
Checking that failure(s) are order-dependent... failure appears to be order-dependent

Round 1: bisecting over non-failing examples 1-2287 .. ignoring examples 1145-2287 (2 minutes 0.9 seconds)
Round 2: bisecting over non-failing examples 1-1144 . ignoring examples 1-572 (41.69 seconds)
Round 3: bisecting over non-failing examples 573-1144 . ignoring examples 573-858 (12.71 seconds)
Round 4: bisecting over non-failing examples 859-1144 .. ignoring examples 1002-1144 (19.57 seconds)
Round 5: bisecting over non-failing examples 859-1001 . ignoring examples 859-930 (8.5 seconds)
Round 6: bisecting over non-failing examples 931-1001 .. ignoring examples 967-1001 (15.09 seconds)
Round 7: bisecting over non-failing examples 931-966 . ignoring examples 931-948 (7.2 seconds)
Round 8: bisecting over non-failing examples 949-966 . ignoring examples 949-957 (7.19 seconds)
Round 9: bisecting over non-failing examples 958-966 . ignoring examples 958-962 (7.34 seconds)
Round 10: bisecting over non-failing examples 963-966 .. ignoring examples 965-966 (13.64 seconds)
Round 11: bisecting over non-failing examples 963-964 .. ignoring example 964 (12.46 seconds)
Bisect complete! Reduced necessary non-failing examples from 2287 to 1 in 4 minutes 32.2 seconds.

The minimal reproduction command is:
  rspec ./spec/mailers/memberships/leave_zusatzsektion_mailer_spec.rb[1:1] ./spec/resources/group/reads_spec.rb[1:2:5:1,1:2:5:2] --tag ~type:feature --seed 106
```
